### ISSUE TITLE
HW32.Packed false positive

### ISSUE THREAD

**Issue by carlosnewmusic** [assap-org/assap#38]
https://www.virustotal.com/gui/file/8b1f2468ff83265b4b6b0df1e10fbba240852fceba771985b40f3d8f0f55f3bf/detection
Bkav Antivirus
![imagen](https://user-images.githubusercontent.com/19379457/55905675-c487ba80-5bd2-11e9-8f6f-98ef5dea3638.png)

**Comment by nereasainzdelamaza** [comment]
Thanks for your comment!

This false positive is probably due to the fact of using the `Windows Command Line` for the following actions:
* Brightness changes: 
    * `powershell (Get-WmiObject -Namespace root/WMI -Class WmiMonitorBrightnessMethods).WmiSetBrightness(1,100)`

    * `powershell (Get-WmiObject -Namespace root/WMI -Class WmiMonitorBrightnessMethods).WmiSetBrightness(1,1)`

* Lock screen: 
    * `rundll32.exe user32.dll,LockWorkStation`

This code can be found on the file  that can be found [here](https://github.com/assap-org/assap/blob/master/src/utils/actions.js).

**Comment by carlosnewmusic** [comment]
because yes, it must be that it is taken as false positive, they could also try to contact the antivirus that mark it as PUA, or sign the executable
